TARGET=gsfxr

INCS += ../../../Sdk/include
INCS += ../../../Sdk/include/gideros
INCS += ../../../libgideros
INCS += ../../../libgid/include
INCS += ../../../luabinding
INCS += ../../../$(LUA_INCLUDE)


SRCS+= Common/gaudio-loader-sfx Common/retrosfxvoice

#LIBS += -L"../../../Sdk/lib/desktop" -llua -lgid -lgideros -lgvfs

include $(ROOT)/scripts/GidLinuxPlugin.mk
