TARGET=controller
SRCS=controller controllerbinder gamepad/Gamepad_private gcontroller gamepad/Gamepad_windows_mm
CFLGS+=-DGID_LIBRARY -DWIN32_NOQT -I.. -I../gamepad
LFLGS+=-lwinmm
include $(ROOT)/scripts/GidWin32Plugin.mk
