cp ../libgid/libgid.dylib "MacOSXTemplate.app/Contents/Frameworks"
cp ../libgideros/libgideros.dylib "MacOSXTemplate.app/Contents/Frameworks"
cp ../libgvfs/libgvfs.dylib "MacOSXTemplate.app/Contents/Frameworks"
cp ../lua/liblua.dylib "MacOSXTemplate.app/Contents/Frameworks"
cp ../libpystring/libpystring.dylib "MacOSXTemplate.app/Contents/Frameworks"