TARGET=Gsfxr
INCS= ../../../Sdk/include
INCS += ../../../Sdk/include/gideros
INCS += ../../../libgideros
INCS += ../../../libgid/include
INCS += ../../../luabinding
INCS += ../../../$(LUA_INCLUDE)


SRCS+= Common/gaudio-loader-sfx Common/retrosfxvoice

include ../../../../emscripten/Plugin.mk
