CPPPATH = [
"../libpng",
"../zlib",
"../libgid/src",
"../libsound",
"../pystring",
"../libpvrt",
"."]

CCFLAGS = ['-Wall', '-g']

Library('lib2dsg', [Glob('*.cpp'), 'gpc.c', Glob('GLES/*.cpp')], CPPPATH=CPPPATH, CCFLAGS=CCFLAGS)
