source 'https://github.com/CocoaPods/Specs.git'
target 'iOS Template iOS' do
#TAG-GIDEROS-POD-IOS
end
target 'iOS Template AppleTV' do
#TAG-GIDEROS-POD-ATV
end
target 'iOS Template Mac' do
#TAG-GIDEROS-POD-MAC
end

