cp ../libgid/libgid.dylib "Gideros Player.app/Contents/Frameworks"
cp ../libgideros/libgideros.dylib "Gideros Player.app/Contents/Frameworks"
cp ../libgvfs/libgvfs.dylib "Gideros Player.app/Contents/Frameworks"
cp ../lua/liblua.dylib "Gideros Player.app/Contents/Frameworks"
cp ../libpystring/libpystring.dylib "Gideros Player.app/Contents/Frameworks"