git checkout -- plugins/ads/source/Android/libs/InMobi-4.1.1.jar
git checkout -- plugins/ads/source/Android/libs/JoyAdUnion.jar
git checkout -- plugins/ads/source/Android/libs/MMSDK.jar
git checkout -- plugins/ads/source/Android/libs/SamsungAdHub_AndroidSDK_v3.0.0_global.jar
git checkout -- plugins/ads/source/Android/libs/TapForTap.jar
git checkout -- plugins/ads/source/Android/libs/adcolony.jar
git checkout -- plugins/ads/source/Android/libs/amazon-ads-5.4.46.jar
git checkout -- plugins/ads/source/Android/libs/applovin-sdk-6.0.0.jar
git checkout -- plugins/ads/source/Android/libs/armeabi/libImmEndpointWarpJ.so
git checkout -- plugins/ads/source/Android/libs/chartboost.jar
git checkout -- plugins/ads/source/Android/libs/heyzap-ads-sdk.jar
git checkout -- plugins/ads/source/Android/libs/mopub-sdk.jar
git checkout -- plugins/ads/source/Android/libs/nmdp_speech_kit.jar
git checkout -- plugins/ads/source/Android/libs/revmob-6.9.6.jar
git checkout -- plugins/ads/source/Android/libs/tapjoyconnectlibrary.jar
git checkout -- plugins/ads/source/Android/libs/vungle/dagger-1.2.2.jar
git checkout -- plugins/ads/source/Android/libs/vungle/javax.inject-1.jar
git checkout -- plugins/ads/source/Android/libs/vungle/nineoldandroids-2.4.0.jar
git checkout -- plugins/ads/source/Android/libs/vungle/vungle-publisher-adaptive-id-3.3.3.jar
git checkout -- plugins/controller/source/Android/libs/com.bda.controller.jar
