TARGET=liquidfun

INCS += ../../../Sdk/include/gideros
INCS += ../../../2dsg
INCS += ../../../2dsg/gfxbackends
INCS += ../../../libgideros
INCS += ../../../libgid/include
INCS += ../../../luabinding
INCS += ../../../lua/src
INCS += liquidfun/Box2D
SRCS += $(addprefix common/,lfstatus liquidfunbinder lqParticles lqSprites lqWorld)
SRCS+=  ../../../luabinding/binder \
   		../../../2dsg/Matrices
SRCS+= \
	liquidfun/Box2D/Box2D/Collision/b2BroadPhase \
	liquidfun/Box2D/Box2D/Collision/b2CollideCircle \
	liquidfun/Box2D/Box2D/Collision/b2CollideEdge \
	liquidfun/Box2D/Box2D/Collision/b2CollidePolygon \
	liquidfun/Box2D/Box2D/Collision/b2Collision \
	liquidfun/Box2D/Box2D/Collision/b2Distance \
	liquidfun/Box2D/Box2D/Collision/b2DynamicTree \
	liquidfun/Box2D/Box2D/Collision/b2TimeOfImpact \
	liquidfun/Box2D/Box2D/Collision/Shapes/b2ChainShape \
	liquidfun/Box2D/Box2D/Collision/Shapes/b2CircleShape \
	liquidfun/Box2D/Box2D/Collision/Shapes/b2EdgeShape \
	liquidfun/Box2D/Box2D/Collision/Shapes/b2PolygonShape \
	liquidfun/Box2D/Box2D/Common/b2BlockAllocator \
	liquidfun/Box2D/Box2D/Common/b2Draw \
	liquidfun/Box2D/Box2D/Common/b2FreeList \
	liquidfun/Box2D/Box2D/Common/b2Math \
	liquidfun/Box2D/Box2D/Common/b2Settings \
	liquidfun/Box2D/Box2D/Common/b2StackAllocator \
	liquidfun/Box2D/Box2D/Common/b2Stat \
	liquidfun/Box2D/Box2D/Common/b2Timer \
	liquidfun/Box2D/Box2D/Common/b2TrackedBlock \
	liquidfun/Box2D/Box2D/Dynamics/b2Body \
	liquidfun/Box2D/Box2D/Dynamics/b2ContactManager \
	liquidfun/Box2D/Box2D/Dynamics/b2Fixture \
	liquidfun/Box2D/Box2D/Dynamics/b2Island \
	liquidfun/Box2D/Box2D/Dynamics/b2World \
	liquidfun/Box2D/Box2D/Dynamics/b2WorldCallbacks \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2ChainAndCircleContact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2CircleContact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2Contact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2ContactSolver \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact \
	liquidfun/Box2D/Box2D/Dynamics/Contacts/b2PolygonContact \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2DistanceJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2FrictionJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2GearJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2Joint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2MotorJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2MouseJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2PrismaticJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2PulleyJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2RevoluteJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2RopeJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2WeldJoint \
	liquidfun/Box2D/Box2D/Dynamics/Joints/b2WheelJoint \
	liquidfun/Box2D/Box2D/Particle/b2Particle \
	liquidfun/Box2D/Box2D/Particle/b2ParticleGroup \
	liquidfun/Box2D/Box2D/Particle/b2ParticleSystem \
	liquidfun/Box2D/Box2D/Particle/b2VoronoiDiagram \
	liquidfun/Box2D/Box2D/Rope/b2Rope

include $(ROOT)/scripts/GidWin32Plugin.mk
