TARGET=camera

INCS += ../../../Sdk/include/gideros
INCS += ../../../2dsg
INCS += ../../../2dsg/gfxbackends
INCS += ../../../libgideros
INCS += ../../../libgid/include
INCS += ../../../luabinding
INCS += ../../../$(LUA_INCLUDE)
INCS += ../../../libgid/external/jpeg-9

INCS += common

SRCS+= ../common/camerabinder gcameraplugin

LIBS=-lgid -lgideros

include $(ROOT)/scripts/GidLinuxPlugin.mk
