TARGET=luasocket
SRCS=auxiliar buffer except inet io luasocket options select tcp timeout udp mime luasocket_stub wsocket 
CFLGS=-DLUA_NOCOMPAT_MODULE -DLUASOCKET_INET_PTON
LFLGS=-lws2_32
include $(ROOT)/scripts/GidWin32Plugin.mk
